name: Running tests when pull request make to branch develop

on: 
  pull_request:
    branches: ["develop"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Using node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: install modules of project
        run: npm install
      
      - name: run tests of project
        run: npm run test

  