name: Pipeline of staging

on: 
  push:
    branches: ["develop"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Using node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules of project
        run: npm install --only=production
        
      - name: Say hello world  
        run: echo 'Hello world'
